{{- if .Values.NetworkPolicy.Enabled }}
---
kind: NetworkPolicy
apiVersion: {{ template "cockroachdb.networkPolicy.apiVersion" . }}
metadata:
  name: "{{ template "cockroachdb.fullName" . }}"
  labels:
    heritage: {{ template "cockroachdb.heritageName" . }}
    release: {{ template "cockroachdb.releaseName" . }}
    chart: {{ template "cockroachdb.chartName" . }}
    component: {{ template "cockroachdb.componentName" . }}
spec:
  podSelector:
    matchLabels:
      component: {{ template "cockroachdb.componentName" . }}
  ingress:
  - ports:
    - port: {{ .Values.ExternalGrpcPort}}
    {{- if not .Values.NetworkPolicy.AllowExternal }}
    from:
    # Allow clients to connect.
    - podSelector:
        matchLabels:
          {{ template "cockroachdb.clientName" . }}: "true"
    # Allow other cockroachdb's to connect to form cluster.
    - podSelector:
        matchLabels:
          component: {{ template "cockroachdb.componentName" . }}
    {{- end }}
  {{- if ne .Values.InternalGrpcPort .Values.ExternalGrpcPort }}
  - ports:
    - port: {{ .Values.InternalGrpcPort}}
    from:
    # Allow other cockroachdb's to connect to form cluster.
    - podSelector:
        matchLabels:
          component: {{ template "cockroachdb.componentName" . }}
  {{- end }}
  # Allow connections to admin UI.
  - ports:
    - port: {{.Values.ExternalHttpPort}}
  # Allow connections from Prometheus.
  - ports:
    - port: {{.Values.ExternalHttpPort}}
{{- end }}
